<a href="https://colab.research.google.com/github/waheed-alam007/Data_analytics_Decodelabe/blob/main/Data_analytics01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/Dataset for Data Analytics.xlsx")

In [ ]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [ ]:
# check the missing values
print("Missing Values in Each Column:")
df.isnull().sum()

Missing Values in Each Column:

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
# fill the missing values
# This fills ALL missing values in the entire DataFrame with 0.
# Applies to every column (numeric, text, etc.)
# inplace=True means it directly updates df (no need to reassign)
df.fillna(0, inplace=True)

In [ ]:
#  This fills missing values (NaN) only in the CouponCode column.
# If a row has no coupon (NaN), it becomes: "No Coupon"
#  Keeps the column meaningful (since it's text data)
df['CouponCode'] = df['CouponCode'].fillna("No Coupon")

In [ ]:
# now i have to remove the missing values
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
# now i  have to check the duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
# in this if you want to show the message plus the how many rows empty then  use this both above line of code judt dhoe the nmbr of empty rows and this below line also give the message and nmbr of row
print("Duplicate Rows Found:", df.duplicated().sum())

Duplicate Rows Found: 0

In [ ]:
# now remove the duplicate rows
df = df.drop_duplicates()

In [ ]:
# Check Duplicate Order IDs
df = df.drop_duplicates(subset='OrderID')

In [ ]:
# now standardize the date format
df['Date'] = pd.to_datetime(df['Date']).dt.strftime('%Y-%m-%d')
# verify date format
print(df['Date'].head())

0    2023-01-04
1    2024-08-23
2    2024-02-27
3    2023-10-15
4    2025-05-08
Name: Date, dtype: object

In [ ]:
# now  i have to clean the txt cloumns Remove Extra Spaces
text_columns = ['Product', 'PaymentMethod', 'OrderStatus', 'ReferralSource']

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
print("FINAL VALIDATION REPORT")
print("-" * 30)

print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nDuplicate Order IDs:", df['OrderID'].duplicated().sum())

FINAL VALIDATION REPORT
------------------------------
Missing Values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

Duplicate Rows: 0

Duplicate Order IDs: 0

In [ ]:
df.to_excel("Cleaned_Dataset.xlsx", index=False)

In [ ]:
files.download("Cleaned_Dataset.xlsx")